name: ci/cd

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.yml'
  pull_request: {}

env:
  VERSION_FILE_PATH: src/Directory.Build.props
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  TAG_COMMIT: false
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "2.2.x"

      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "3.1.x"

      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "5.0.x"

      - name: run unit tests
        run: dotnet test src/

      - name: publish FairyBread on version change
        if: github.ref.endsWith('master') || github.ref.endsWith('main')
        uses: rohith/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/FairyBread/FairyBread.csproj
          TAG_COMMIT: true
