name: publish to nuget
on:
  push:
    branches:
      - master
env:
  VERSION_FILE_PATH: src/Directory.Build.props
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  TAG_COMMIT: false
jobs: 
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        
      - name: publish FairyBread on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/FairyBread/FairyBread.csproj
          TAG_COMMIT: true
